# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 paths:
  include:
    - ui-community
 branches:
   include:
     - main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - ui-community

variables:
## PROJECT SPECIFIC VARIABLES - start
    PROJECT_NAME: 'ui-community'
    # Skip SonarCloud tasks if 'disableSonarCloudTasks' is set to True
    disableSonarCloudTasks: 'false'
    # SonarCloud configuration 
    SonarCloud: 'SonarCloud'
    SonarCloud_organization: 'simnova'
    SONARCLOUD_PROJECT_KEY: 'oc-ui'
    SONARCLOUD_PROJECT_NAME: 'oc-ui'
    vmImageName: 'ubuntu-latest'
## PROJECT SPECIFIC VARIABLES - end
    system.debug: true
    npm_config_cache: $(Pipeline.Workspace)/.npm
    SONAR_USER_HOME: $(Pipeline.Workspace)/.sonar
    subscription: 'OwnerCommunity'
    #dev
    environmentNameDev: 'oc-dev'
    ResourceGroupNameDev: 'rg-owner-community'
    destinationBlobContainerDev: 'ocdevstuicrjyobt6kbghbk'
    cdnProfileDev: 'cdn-dev-ms-standard'
    cdnNameDev: 'oc-dev-cdne-uia-rjyobt6kbghbk'
    #prod
    environmentNamePrd: 'oc-prd'
    ResourceGroupNamePrd: 'corp-prod-rg'
    destinationBlobContainerPrd: 'ocprdstuialbiusbw5zdgpc'
    cdnProfilePrd: 'cdn-prod-ms-standard'
    cdnNamePrd: 'oc-prd-cdne-uia-lbiusbw5zdgpc'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: dev_build_stage
  displayName: Build Stage
  jobs:
  - job: build_job
    displayName: Build Job
    steps:

    - template: ./build-pipeline/cra-npm-build.yml
      parameters: 
        buildPath: $(PROJECT_NAME)
        archivePath: $(PROJECT_NAME)/build
        archiveName: $(environmentNameDev)
        npmVersion: '18.x'
        buildEnvSettings: 
          INLINE_RUNTIME_CHUNK: 'false'
          VITE_FUNCTION_ENDPOINT: $(VITE_FUNCTION_ENDPOINT_DEV)
          VITE_APP_INSIGHTS_CONNECTION_STRING: $(VITE_APP_INSIGHTS_CONNECTION_STRING_DEV)
          VITE_AAD_B2C_ACCOUNT_CLIENTID: $(VITE_AAD_B2C_ACCOUNT_CLIENTID_DEV)
          VITE_AAD_ACCOUNT_CLIENTID: $(VITE_AAD_ACCOUNT_CLIENTID_DEV)
          VITE_AAD_B2C_ACCOUNT_AUTHORITY: $(VITE_AAD_B2C_ACCOUNT_AUTHORITY_DEV)
          VITE_AAD_ACCOUNT_AUTHORITY: $(VITE_AAD_ACCOUNT_AUTHORITY_DEV)
          VITE_AAD_B2C_ACCOUNT_SCOPES: $(VITE_AAD_B2C_ACCOUNT_SCOPES_DEV)
          VITE_AAD_ACCOUNT_SCOPES: $(VITE_AAD_ACCOUNT_SCOPES_DEV)
          VITE_AAD_B2C_REDIRECT_URI: $(VITE_AAD_B2C_REDIRECT_URI_DEV)
          VITE_AAD_REDIRECT_URI: $(VITE_AAD_REDIRECT_URI_DEV)
          VITE_PORTAL_IDENTIFIER: $(VITE_PORTAL_IDENTIFIER)
          VITE_FEATURE_FLAG_URL: $(VITE_FEATURE_FLAG_URL_DEV)
          VITE_TIMEOUT_BEFORE_MAINTENANCE: $(VITE_TIMEOUT_BEFORE_MAINTENANCE_DEV)

    - task: Cache@2
      displayName: Cache SonarCloud
      condition: and(succeeded(), eq(variables['disableSonarCloudTasks'], False))
      inputs:
        key: 'sonarcloud | "$(Agent.OS)"'
        restoreKeys: |
            sonarcloud | "$(Agent.OS)"
        path: $(SONAR_USER_HOME)/cache

    - task: SonarCloudPrepare@2
      displayName: 'SonarCloud: Prepare analysis configuration'
      condition: and(succeeded(), eq(variables['disableSonarCloudTasks'], False))
      inputs:
        SonarCloud: $(SonarCloud)
        organization: $(SonarCloud_organization)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(SONARCLOUD_PROJECT_KEY)
        cliProjectName: $(SONARCLOUD_PROJECT_NAME)
        cliSources: './$(PROJECT_NAME)/src'

    
        # Publish chromatic
    # - task: Bash@3
    #   condition: ne(variables['Build.Reason'], 'PullRequest')
    #   displayName: 'chromatic build'
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --auto-accept-changes --allow-console-errors
    #     workingDirectory: 'ui'
    #   env: 
    #     NODE_OPTIONS: --max_old_space_size=16384   
    #     INLINE_RUNTIME_CHUNK: 'false'
    #     VITE_FUNCTION_ENDPOINT: $(VITE_FUNCTION_ENDPOINT_DEV)
    #     VITE_APP_INSIGHTS_CONNECTION_STRING: $(VITE_APP_INSIGHTS_CONNECTION_STRING_DEV)
    #     VITE_AAD_ACCOUNT_CLIENTID: $(VITE_AAD_ACCOUNT_CLIENTID_DEV)
    #     VITE_AAD_ACCOUNT_AUTHORITY: $(VITE_AAD_ACCOUNT_AUTHORITY_DEV)
    #     VITE_AAD_ACCOUNT_SCOPES: $(VITE_AAD_ACCOUNT_SCOPES_DEV)
    #     VITE_AAD_REDIRECT_URI: $(VITE_AAD_REDIRECT_URI_DEV)
    #     VITE_PORTAL_IDENTIFIER: $(VITE_PORTAL_IDENTIFIER)
    #     VITE_FEATURE_FLAG_URL: $(VITE_FEATURE_FLAG_URL_DEV)
    #     VITE_TIMEOUT_BEFORE_MAINTENANCE: $(VITE_TIMEOUT_BEFORE_MAINTENANCE_DEV)

    - task: SonarCloudAnalyze@2
      displayName: 'SonarCloud: Run analysis'
      condition: and(succeeded(), eq(variables['disableSonarCloudTasks'], False))

    - task: SonarCloudPublish@2
      displayName: 'SonarCloud: Publish results on build summary'
      condition: and(succeeded(), eq(variables['disableSonarCloudTasks'], False))
      inputs:
        pollingTimeoutSec: '300'

    # SonarCloud: Break the build if it doesn't pass the Quality Gate
    - task: sonarcloud-buildbreaker@2
      displayName: 'SonarCloud: Break the build if it does not pass the Quality'
      condition: and(succeeded(), eq(variables['disableSonarCloudTasks'], False))
      inputs:
        SonarCloud: $(SonarCloud)
        organization: $(SonarCloud_organization)
        
    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'www'
        publishLocation: 'Container'

    

- stage: build_prd_stage
  displayName: Build prd Stage
  dependsOn: build_dev_infrastructure
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: build_job
    displayName: Build Job
    steps:

    #build PRD
    - template: ./build-pipeline/cra-npm-build.yml
      parameters: 
        buildPath: $(PROJECT_NAME)
        archivePath: $(PROJECT_NAME)/build
        archiveName: $(environmentNamePrd)
        npmVersion: '18.x'
        buildEnvSettings: 
          INLINE_RUNTIME_CHUNK: 'false'
          VITE_FUNCTION_ENDPOINT: $(VITE_FUNCTION_ENDPOINT_PRD)
          VITE_APP_INSIGHTS_CONNECTION_STRING: $(VITE_APP_INSIGHTS_CONNECTION_STRING_PRD)
          VITE_AAD_ACCOUNT_CLIENTID: $(VITE_AAD_ACCOUNT_CLIENTID_PRD)
          VITE_AAD_ACCOUNT_AUTHORITY: $(VITE_AAD_ACCOUNT_AUTHORITY_PRD)
          VITE_AAD_ACCOUNT_SCOPES: $(VITE_AAD_ACCOUNT_SCOPES_PRD)
          VITE_AAD_REDIRECT_URI: $(VITE_AAD_REDIRECT_URI_PRD)
          VITE_PORTAL_IDENTIFIER: $(VITE_PORTAL_IDENTIFIER)
          VITE_FEATURE_FLAG_URL: $(VITE_FEATURE_FLAG_URL_PRD)
          VITE_TIMEOUT_BEFORE_MAINTENANCE: $(VITE_TIMEOUT_BEFORE_MAINTENANCE_PRD)
          VITE_BUILD_VERSION: $(Build.BuildId)
          
    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'www'
        publishLocation: 'Container'     

- stage: build_dev_infrastructure
  displayName: DEV stage
  dependsOn: dev_build_stage
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Infrastructure 
    displayName: Infrastructure Setup 
    pool:
      vmImage: $(vmImageName) 
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: $(subscription)
        deploymentName: $(Build.BuildNumber)
        location: $(deploymentDefaultLocation)
        resourceGroupName: $(ResourceGroupNameDev)
        csmFile: $(PROJECT_NAME)/iac/main.bicep
        overrideParameters: >
              -environment dev
  - deployment: Application
    dependsOn: Infrastructure
    displayName: Application Deployment
    environment: $(environmentNameDev)
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - template: ./build-pipeline/blob-cdn-website-deploy.yml
            parameters:
              subscription: $(subscription)
              destinationBlobContainer: $(destinationBlobContainerDev)
              archiveName: $(environmentNameDev)
              cdnProfile: $(cdnProfileDev)
              cdnResourceGroup: $(ResourceGroupNameDev)
              cdnName: $(cdnNameDev)  

- stage: build_prd_infrastructure
  displayName: PRD infrastructure stage
  dependsOn: build_prd_stage
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Infrastructure 
    displayName: Infrastructure Setup 
    pool:
      vmImage: $(vmImageName) 
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: $(subscription)
        deploymentName: $(Build.BuildNumber)
        location: $(deploymentDefaultLocation)
        resourceGroupName: $(ResourceGroupNamePrd)
        csmFile: $(PROJECT_NAME)/iac/main.bicep
        overrideParameters: >
              -environment prd
  - deployment: Application
    dependsOn: Infrastructure
    displayName: Application Deployment
    environment: $(environmentNamePrd)
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - template: ./build-pipeline/blob-cdn-website-deploy.yml
            parameters:
              subscription: $(subscription)
              destinationBlobContainer: $(destinationBlobContainerPrd)
              archiveName: $(environmentNamePrd)
              cdnProfile: $(cdnProfilePrd)
              cdnResourceGroup: $(ResourceGroupNamePrd)
              cdnName: $(cdnNamePrd)  