parameters:
- name: dependsOnStage
  displayName: 'Depends On Stage'
  type: string
  default: Build
- name: environmentNameDevOps
  displayName: 'Environment Name in DevOps- Dev/QA/UAT/Production/Core'
  type: string
- name: vmImageName
  displayName: 'VM Image - ubuntu-latest'
  type: string
- name: ServiceConnectionName
  displayName: 'Service Connection Name'
  type: string
- name: deploymentDefaultLocation
  displayName: 'Default Location for Deployment'
  type: string
- name: resourceGroupName
  displayName: 'Resource Group Name'
  type: string


stages:
- stage: ${{parameters.environmentNameDevOps}}
  displayName: ${{parameters.environmentNameDevOps}} stage
  dependsOn: ${{parameters.dependsOnStage}}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Infrastructure 
    displayName: Infrastructure Setup 
    pool:
      vmImage: ${{parameters.vmImageName}}
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: ${{parameters.ServiceConnectionName}}
        deploymentName: $(Build.BuildNumber)
        location: ${{parameters.deploymentDefaultLocation}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        csmFile: data-access/iac/core.bicep

              

